version: '3.8'

services:

  database:
    image: postgres:15
    container_name: payment_service_database
    restart: always
    environment:
      TZ: 'America/Sao_Paulo'
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    healthcheck: #verificação da saúde do container
      test: ["CMD-SHELL", "pg_isready -U postgres"] #testa o postgres com o comando esperando uma resposta
      interval: 5s #intervalo de tempo
      timeout: 5s #tempo maximo de espera
      retries: 5 # numero de tentativas
    networks:
      - payment_service_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment_service_app:latest
    container_name: payment_service_app
    ports:
      - "3003:3003"
    env_file:
      - .env.docker
    depends_on:
      database:
        condition: service_healthy #inicia o container do app só quando o postgres disser que está healthy
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - payment_service_network
    profiles:
      - all

networks:
  payment_service_network:
    driver: bridge
